// Generated by CoffeeScript 1.9.2
var broadcast;

broadcast = {
  on: function(name, fn) {
    var eventData;
    eventData = broadcast.data;
    if (eventData.hasOwnProperty(name)) {
      return eventData[name].push(fn);
    } else {
      return eventData[name] = [fn];
    }
  },
  fire: function(name, data, thisArg) {
    var fn, fnList, i, len, results;
    thisArg = thisArg || window;
    fnList = broadcast.data[name];
    if (!fnList.length) {
      throw new Error("Cannot find broadcast event " + name);
    }
    results = [];
    for (i = 0, len = fnList.length; i < len; i++) {
      fn = fnList[i];
      results.push(fn.apply(thisArg, [data, name]));
    }
    return results;
  },
  data: {}
};

module.exports = broadcast;
